Foo

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,6 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(libsrs/srs.h)
-AM_INIT_AUTOMAKE(libsrs, 1.0.4)
+AM_INIT_AUTOMAKE(libsrs2, 1.0.6)
 
 dnl Checks for programs.
 AC_PROG_CC
@@ -9,13 +9,20 @@ AC_PROG_MAKE_SET
 AC_PROG_RANLIB
 AC_PROG_LIBTOOL
 
-dnl Checks for libraries.
-dnl Replace `main' with a function in -lcrypto:
-AC_CHECK_LIB(crypto, EVP_sha1)
-
 dnl Checks for header files.
 AC_HEADER_STDC
-AC_CHECK_HEADERS(strings.h sys/time.h unistd.h ssl.h openssl/ssl.h)
+AC_CHECK_HEADERS(strings.h sys/time.h unistd.h)
+AC_CHECK_HEADER(openssl/ssl.h, , [
+	echo "OpenSSL is required to build this library."
+	exit 1;
+])
+
+dnl Checks for libraries.
+dnl Replace `main' with a function in -lcrypto:
+AC_CHECK_LIB(crypto, EVP_sha1, , [
+	echo "OpenSSL is required to build this library."
+	exit 1;
+])
 
 dnl Checks for typedefs, structures, and compiler characteristics.
 AC_C_CONST
